# Importations

In [13]:

import matplotlib.pyplot as plt
import sys
from IPython.core import ultratb
import dill
import numpy as np
from functions_synthetic_data_generation import *
from functions_synthetic_data_analysis import *
sys.excepthook = ultratb.FormattedTB(call_pdb=False)

plt.style.use('../paper.mplstyle')

print(plt.get_backend())
%matplotlib qt5
print(plt.get_backend())

qt5agg
qt5agg


# Parameters

In [14]:
simulations_folder_path = '/home/david/Documents/code/DDM_vX_synthetic_data_identical_drift'
n_simulations = 50
batch_index = 9
simulations_indexes = np.arange(n_simulations)

with open(f'{simulations_folder_path}/n_{n_simulations}/simulations_batch_{n_simulations}_test_{batch_index+1}.pkl', 'rb') as file:
    synthetic_data = dill.load(file)

test_data = [synth_data['choices'] for synth_data in synthetic_data]

# Plots

## All simulations

In [15]:
fig=plt.figure(figsize=(4, 2), dpi=300, constrained_layout=False, facecolor='w')
gs = fig.add_gridspec(1, 1, hspace=0.5,)
row = gs[0,0].subgridspec(2, 1)


for i, simulation_index in enumerate(simulations_indexes):

    ddm_result = synthetic_data[simulation_index]

    choice_sequence = ddm_result['choices']
    p_cw_sequence = ddm_result['p_cw']
    reward_sequence = ddm_result['rewards']

    steps = np.arange(len(choice_sequence))

    colors = ['violet' if i==1 else 'purple' for i in reward_sequence]

    ax1 = plt.subplot(row[0,0])
    ax1.scatter(steps, choice_sequence, label='Action Sequence', color=colors, marker='+')
    ax1.set_ylabel('Action')
    ax1.set_xticks([])
    ax1.set_yticks([0,1])
    ax1.set_yticklabels(['CCW','CW'])

    ax2 = plt.subplot(row[1,0])
    ax2.plot(steps, p_cw_sequence, label='Probability Sequence', alpha=0.2)
    
    ax2.set_xlabel('Step')
    ax2.set_ylabel('Probability\nto do CW')
    ax2.set_xticks(steps[::5])
    ax2.set_ylim([-0.05,1.05])

plt.show()

## One simulation

In [16]:
fig=plt.figure(figsize=(4, 2), dpi=300, constrained_layout=False, facecolor='w')
gs = fig.add_gridspec(1, 1, hspace=0.5,)
row = gs[0,0].subgridspec(2, 1)

simulation_index = 10

ddm_result = synthetic_data[simulation_index]

choice_sequence = ddm_result['choices']
p_cw_sequence = ddm_result['p_cw']
reward_sequence = ddm_result['rewards']

steps = np.arange(len(choice_sequence))

colors = ['violet' if i==1 else 'indigo' for i in reward_sequence]

ax1 = plt.subplot(row[0,0])
ax1.scatter(steps, choice_sequence, label='Action Sequence', color=colors, marker='+')
ax1.set_ylabel('Action')
ax1.set_xticks([])
ax1.set_yticks([0,1])
ax1.set_yticklabels(['CCW','CW'])

ax2 = plt.subplot(row[1,0])
ax2.plot(steps, p_cw_sequence, label='Probability Sequence', alpha=0.2)

ax2.set_xlabel('Step')
ax2.set_ylabel('Probability\nto do CW')
ax2.set_xticks(steps[::5])
ax2.set_ylim([-0.05,1.05])

plt.show()

## Probability distribution

In [60]:
fig=plt.figure(figsize=(4, 2), dpi=300, constrained_layout=False, facecolor='w')
gs = fig.add_gridspec(1, 1, hspace=0.5,)
row = gs[0,0].subgridspec(1, 1)
ax1 = plt.subplot(row[0,0])

stacked_proba_sequences_list = []

for i, simulation_index in enumerate(simulations_indexes):

    ddm_result = synthetic_data[simulation_index]

    choice_sequence = ddm_result['choices']
    p_cw_sequence = ddm_result['p_cw']
    reward_sequence = ddm_result['rewards']

    stacked_proba_sequences_list.append(p_cw_sequence)

bin_edges = np.linspace(-0.1, 1, 100) 

counts_list = []

for j in range(len(stacked_proba_sequences_list)):

    counts = np.zeros(len(bin_edges))

    for proba in stacked_proba_sequences_list[j]:

        for n in range(len(bin_edges)-1):

            if bin_edges[n] < proba <= bin_edges[n+1]:

                counts[n] += 1

    counts_list.append(counts)

    # print(np.sum(counts))


# binned_proba_sequence = []

# for j in range(len(stacked_proba_sequences_list)):


#     bin_indices = np.digitize(stacked_proba_sequences_list[j], bin_edges)

#     binned_proba_sequence.append(np.histogram(bin_indices,bin_edges)[0])

ax1.imshow(np.transpose(counts_list))

# stacked_proba_sequences_arr = np.tanspose(np.array(stacked_proba_sequences_list))

# ax1.scatter(steps, stacked_proba_sequences_arr[i], label='Action Sequence', color=colors, marker='+')
# ax1.set_ylabel('Action')
# # ax1.set_xticks([])
# # ax1.set_yticks([0,1])
# ax1.set_yticklabels(['CCW','CW'])


    # steps = np.arange(len(choice_sequence))

    # colors = ['violet' if i==1 else 'purple' for i in reward_sequence]

    # ax1 = plt.subplot(row[0,0])
    # ax1.scatter(steps, choice_sequence, label='Action Sequence', color=colors, marker='+')
    # ax1.set_ylabel('Action')
    # ax1.set_xticks([])
    # ax1.set_yticks([0,1])
    # ax1.set_yticklabels(['CCW','CW'])

    # ax2 = plt.subplot(row[1,0])
    # ax2.plot(steps, p_cw_sequence, label='Probability Sequence', alpha=0.2)
    
    # ax2.set_xlabel('Step')
    # ax2.set_ylabel('Probability\nto do CW')
    # ax2.set_xticks(steps[::5])
    # ax2.set_ylim([-0.05,1.05])


In [58]:
counts

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  2.,  0.,  1.,
        4.,  0.,  1.,  1.,  0.,  0.,  1., 25.,  0.])

In [12]:
test = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [10,11,12]])

print(np.transpose(test))

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
